# Chance to drop
dropChance:
  diamond: 0.2
  emerald: 0.5
  redstone: 1
  lapis: 1
  gold: 1.5
  iron: 1.8
  coal: 2.2
  cobblestone: 100

# Exp from drop
exp:
  diamond: 5
  emerald: 5
  redstone: 4
  lapis: 4
  gold: 3
  iron: 3
  coal: 2
  cobblestone: 0

# Displayed name (Don't use color (&))
name:
  diamond: Diament
  emerald: Emerald
  redstone: Redstone
  lapis: Lapis
  gold: Zloto
  iron: Zelazo
  coal: Wegiel
  cobblestone: Cobblestone

# Vip extra chance
vipChance: 2

# TurboDrop extra chance
turboDropChance: 3

