name: cDrop
version: 1.0;
description: cDrop plugin by CubeStorm
author: CubeStorm
main: pl.cubestorm.cdrop.Main
api-version: 1.16
commands:
  drop:
    description: Drop plugin by CubeStorm
    usage: /drop